#!/usr/bin/env python3
"""Generate fsdata_custom.c from web/ files for lwIP httpd.

Usage: python3 tools/makefsdata.py web gen/fsdata_custom.c

Generates a C file that lwIP httpd #includes via HTTPD_FSDATA_FILE.
Designed for LWIP_HTTPD_DYNAMIC_HEADERS=1 (no HTTP headers in data).
"""

import os
import sys


def make_varname(path):
    """Convert /index.html -> file__index_html"""
    return 'file_' + path.replace('/', '_').replace('.', '_').replace('-', '_')


def to_c_array(data, varname):
    lines = [f'static const unsigned char {varname}[] = {{']
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hex_vals = ', '.join(f'0x{b:02x}' for b in chunk)
        lines.append(f'  {hex_vals},')
    lines.append('};')
    return '\n'.join(lines)


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <web_dir> <output.c>")
        sys.exit(1)

    web_dir = sys.argv[1]
    output = sys.argv[2]

    files = []
    for root, dirs, filenames in os.walk(web_dir):
        for fn in sorted(filenames):
            full = os.path.join(root, fn)
            rel = '/' + os.path.relpath(full, web_dir)
            files.append((rel, full))

    if not files:
        print("No files found!")
        sys.exit(1)

    out_lines = []
    out_lines.append('/* Auto-generated by makefsdata.py — do not edit */')
    out_lines.append('#include "lwip/apps/fs.h"')
    out_lines.append('')

    file_entries = []
    for path, fullpath in files:
        varname = make_varname(path)

        with open(fullpath, 'rb') as f:
            content = f.read()

        out_lines.append(to_c_array(content, varname + '_data'))
        out_lines.append('')

        file_entries.append({
            'path': path,
            'varname': varname,
            'data_len': len(content),
        })

    # File name arrays
    for entry in file_entries:
        path_bytes = entry['path'].encode('ascii') + b'\x00'
        out_lines.append(to_c_array(path_bytes, entry['varname'] + '_name'))
        out_lines.append('')

    # Struct chain (reverse order so forward refs are satisfied)
    for i in range(len(file_entries) - 1, -1, -1):
        entry = file_entries[i]
        next_ref = '&' + file_entries[i+1]['varname'] + '[0]' if i + 1 < len(file_entries) else 'NULL'
        out_lines.append(f'const struct fsdata_file {entry["varname"]}[] = {{{{')
        out_lines.append(f'  {next_ref},')
        out_lines.append(f'  {entry["varname"]}_name,')
        out_lines.append(f'  {entry["varname"]}_data,')
        out_lines.append(f'  {entry["data_len"]},')
        out_lines.append(f'  0,')  # flags=0: no headers included, dynamic headers mode
        out_lines.append(f'}}}};')
        out_lines.append('')

    out_lines.append(f'#define FS_ROOT {file_entries[0]["varname"]}')
    out_lines.append(f'#define FS_NUMFILES {len(file_entries)}')

    os.makedirs(os.path.dirname(os.path.abspath(output)), exist_ok=True)
    with open(output, 'w') as f:
        f.write('\n'.join(out_lines) + '\n')

    print(f"Generated {output}: {len(file_entries)} files")


if __name__ == '__main__':
    main()
